default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: <%= ENV["IST_UR_ORG_DEV_DB"] %>
  username: <%= ENV["IST_UR_ORG_DEV_USR"] %>
  password: <%= ENV["IST_UR_ORG_DEV_PW"] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: <%= ENV["IST_UR_ORG_TEST_DB"] %>
  username: <%= ENV["IST_UR_ORG_DEV_USR"] %>
  password: <%= ENV["IST_UR_ORG_DEV_PW"] %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: <%= ENV["IST_UR_ORG_PROD_DB"] %>
  username: <%= ENV["IST_UR_ORG_PROD_USR"] %>
  password: <%= ENV["IST_UR_ORG_PROD_PW"] %>
  host: localhost
  port: 5432