#development:
#  server: "http://192.168.1.3:9292/faye"
#  secret_token: "secret"
#test:
#  server: "http://localhost:9292/faye"
#  secret_token: "secret"
#production:
#  server: "http://ur-org-faye.herokuapp.com/faye"
#  secret_token: "2260373f1e11a38b4e96dc7638c26e2a5545b85059ff745360385032a13fe911"
#  signature_expiration: 3600 # one hour
